# Generated by Django 2.2.16 on 2022-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220430_1733'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', help_text='укажите уровень прав', max_length=50, verbose_name='права пользователя'),
        ),
    ]
